hosts:
  - name: webserver1
    host: 89.233.108.20
    port: 22
    user: root
    password: "xzasNGn6qF"
    become: true
    become_password: "xzasNGn6qF"

tasks:
  - name: Update apt cache
    apt:
      update_cache: true
      cache_valid_time: 3600

  - name: Install curl
    apt:
      name:
        - curl
      state: present

  - name: Remove btop
    apt:
      name: btop
      state: absent

  - name: Ensure htop is at latest version
    apt:
      name: htop
      state: latest

  # - name: Remove unused packages
  #   apt:
  #     autoremove: true
