hosts:
  - name: webserver1
    host: 89.233.108.20
    port: 22
    user: root
    password: "testpass"
    become: true
    become_password: "testpass"

tasks:
  - name: Add Grafana GPG key
    apt_key:
      url: https://apt.grafana.com/gpg-full.key
      keyring: /etc/apt/keyrings/grafana.asc
      state: present

  - name: Add Grafana repository
    apt_repository:
      repo: "deb [signed-by=/etc/apt/keyrings/grafana.asc] https://apt.grafana.com stable main"
      filename: grafana
      update_cache: true

  - name: Install Alloy
    apt:
      name: alloy
      state: present
